"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Any, Callable

from docling_core.types.doc.base import BoundingBox

if TYPE_CHECKING: ...
TYPE_ATTR = ...
OBJ_TYPES = ...

def encode_obj(obj: Any, chain: Callable | None = ...) -> Any:
    """Convert custom dataclass to dict for serialization."""
    ...

def decode_obj(obj: Any, chain: Callable | None = ...) -> Any:
    """Load custom dataclass from serialized dict."""
    ...

def encode_df(obj: Any, chain: Callable | None = ...) -> Any:
    """Convert pandas.DataFrame for serialization."""
    ...

def decode_df(obj: Any, chain: Callable | None = ...) -> Any:
    """Load pandas.DataFrame from serialized data."""
    ...

def get_bounding_box(
    bbox: BoundingBox, page_height: float
) -> tuple[float, float, float, float]: ...
