"""
This type stub file was generated by pyright.
"""

from .pytesseract import (
    ALTONotSupported,
    Output,
    TesseractError,
    TesseractNotFoundError,
    TSVNotSupported,
    get_languages,
    get_tesseract_version,
    image_to_alto_xml,
    image_to_boxes,
    image_to_data,
    image_to_osd,
    image_to_pdf_or_hocr,
    image_to_string,
    run_and_get_multiple_output,
    run_and_get_output,
)

__version__ = ...
